---
- name: Add repository
  become: true
  apt_repository:
    repo: '{{ repo_url }}'
    state: present

- name: Install ansible
  become: true
  apt:
    update_cache: yes
    pkg: "{{ item }}"
    state: latest
  with_items: "{{software_packages}}"
